feat: make fixture rendering testing work with enigma-mocker
qlik-oss/sn-scatter-plot pull request #105
Opened 2021-11-30 15:04 UTC by LiKang6688

2021-12-08 08:35 UTC, veinfors commented on .circleci/config.yml
> +          path: ./test/regression/artifacts
These tests are still rendering tests, right? So I would prefer we keep having them under `test/rendering`

2021-12-08 08:36 UTC, veinfors requested changes
These tests are still rendering tests, right? So I would prefer we keep having them under test/rendering

2021-12-08 08:39 UTC, veinfors commented
Another thing. Now we have these test cases which are basically "skipped" due to no `qlikcore/engine` being available, and those are the ones I would like us to convert into using fixtures instead. Only then can we continue delivering stuff confidently into this repo. Here is the list:

- test/rendering/artifacts/baseline/mes_2_color_dim.png
- test/rendering/artifacts/baseline/mes_2_color_dim_dim_null.png
- test/rendering/artifacts/baseline/mes_2_color_mes.png
- test/rendering/artifacts/baseline/plugin_axes.png
- test/rendering/artifacts/baseline/plugin_line.png
- test/rendering/artifacts/baseline/plugin_point.png
- test/rendering/artifacts/baseline/scatter_render_1.png
- test/rendering/artifacts/baseline/scatter_render_2.png
- test/rendering/artifacts/baseline/scatter_render_3.png
- test/rendering/artifacts/baseline/scatter_render_4.png
- test/rendering/artifacts/baseline/scatter_render_5.png
- test/rendering/artifacts/baseline/scatter_render_6.png
- test/rendering/artifacts/baseline/scatter_render_7.png
- test/rendering/artifacts/baseline/scatter_render_8.png
- test/rendering/artifacts/baseline/scatter_render_oob1.png

2021-12-08 08:39 UTC, LiKang6688 commented
> These tests are still rendering tests, right? So I would prefer we keep having them under test/rendering

Yes, sure

2021-12-08 11:39 UTC, bao-ho approved these changes

2021-12-09 22:10 UTC, LiKang6688 commented
> These tests are still rendering tests, right? So I would prefer we keep having them under test/rendering

Done. now test cases are converted into fixtures and are under test/rendering

2021-12-10 08:40 UTC, veinfors approved these changes

2021-12-10 12:16 UTC, merged